### ISSUE TITLE
How much resources(RAM & CPU) this deployment occupy ?

### ISSUE THREAD

**Issue by harshmanvar** [HarryEMartland/swagger-ui-kubernetes-example#1]
Can you please share resource usage with this deployment?

Also, i have question if we are keeping YAML or JSON config file inside pod can we access it via URL? Also why you are using PVC & Configmap?

**Comment by HarryEMartland** [comment]
This example does not specify resources. For more information on the image see https://hub.docker.com/r/swaggerapi/swagger-ui It uses Nginx so it should not need much.

I am not sure if you can access the config via a URL but it is not intended to do so.

The example uses a PVC and Config map showing how you can configure it in different ways.

**Comment by harshmanvar** [comment]
Thanks for writing back.
